# Generated by Django 3.1.5 on 2021-02-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210202_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Ask',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/images/'),
        ),
    ]
