# Generated by Django 3.1.5 on 2021-02-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210204_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer2',
            name='parent',
        ),
    ]
