# Generated by Django 3.1.5 on 2021-02-04 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210204_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='blog.ask2')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
